# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/bin/ccmake

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /root/proj/liteco

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /root/proj/liteco

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /root/proj/liteco/CMakeFiles /root/proj/liteco/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /root/proj/liteco/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named liteco

# Build rule for target.
liteco: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 liteco
.PHONY : liteco

# fast build rule for target.
liteco/fast:
	$(MAKE) -f CMakeFiles/liteco.dir/build.make CMakeFiles/liteco.dir/build
.PHONY : liteco/fast

src/channel.o: src/channel.c.o
.PHONY : src/channel.o

# target to build an object file
src/channel.c.o:
	$(MAKE) -f CMakeFiles/liteco.dir/build.make CMakeFiles/liteco.dir/src/channel.c.o
.PHONY : src/channel.c.o

src/channel.i: src/channel.c.i
.PHONY : src/channel.i

# target to preprocess a source file
src/channel.c.i:
	$(MAKE) -f CMakeFiles/liteco.dir/build.make CMakeFiles/liteco.dir/src/channel.c.i
.PHONY : src/channel.c.i

src/channel.s: src/channel.c.s
.PHONY : src/channel.s

# target to generate assembly for a file
src/channel.c.s:
	$(MAKE) -f CMakeFiles/liteco.dir/build.make CMakeFiles/liteco.dir/src/channel.c.s
.PHONY : src/channel.c.s

src/coroutine.o: src/coroutine.c.o
.PHONY : src/coroutine.o

# target to build an object file
src/coroutine.c.o:
	$(MAKE) -f CMakeFiles/liteco.dir/build.make CMakeFiles/liteco.dir/src/coroutine.c.o
.PHONY : src/coroutine.c.o

src/coroutine.i: src/coroutine.c.i
.PHONY : src/coroutine.i

# target to preprocess a source file
src/coroutine.c.i:
	$(MAKE) -f CMakeFiles/liteco.dir/build.make CMakeFiles/liteco.dir/src/coroutine.c.i
.PHONY : src/coroutine.c.i

src/coroutine.s: src/coroutine.c.s
.PHONY : src/coroutine.s

# target to generate assembly for a file
src/coroutine.c.s:
	$(MAKE) -f CMakeFiles/liteco.dir/build.make CMakeFiles/liteco.dir/src/coroutine.c.s
.PHONY : src/coroutine.c.s

src/link.o: src/link.c.o
.PHONY : src/link.o

# target to build an object file
src/link.c.o:
	$(MAKE) -f CMakeFiles/liteco.dir/build.make CMakeFiles/liteco.dir/src/link.c.o
.PHONY : src/link.c.o

src/link.i: src/link.c.i
.PHONY : src/link.i

# target to preprocess a source file
src/link.c.i:
	$(MAKE) -f CMakeFiles/liteco.dir/build.make CMakeFiles/liteco.dir/src/link.c.i
.PHONY : src/link.c.i

src/link.s: src/link.c.s
.PHONY : src/link.s

# target to generate assembly for a file
src/link.c.s:
	$(MAKE) -f CMakeFiles/liteco.dir/build.make CMakeFiles/liteco.dir/src/link.c.s
.PHONY : src/link.c.s

src/machine.o: src/machine.c.o
.PHONY : src/machine.o

# target to build an object file
src/machine.c.o:
	$(MAKE) -f CMakeFiles/liteco.dir/build.make CMakeFiles/liteco.dir/src/machine.c.o
.PHONY : src/machine.c.o

src/machine.i: src/machine.c.i
.PHONY : src/machine.i

# target to preprocess a source file
src/machine.c.i:
	$(MAKE) -f CMakeFiles/liteco.dir/build.make CMakeFiles/liteco.dir/src/machine.c.i
.PHONY : src/machine.c.i

src/machine.s: src/machine.c.s
.PHONY : src/machine.s

# target to generate assembly for a file
src/machine.c.s:
	$(MAKE) -f CMakeFiles/liteco.dir/build.make CMakeFiles/liteco.dir/src/machine.c.s
.PHONY : src/machine.c.s

src/malloc.o: src/malloc.c.o
.PHONY : src/malloc.o

# target to build an object file
src/malloc.c.o:
	$(MAKE) -f CMakeFiles/liteco.dir/build.make CMakeFiles/liteco.dir/src/malloc.c.o
.PHONY : src/malloc.c.o

src/malloc.i: src/malloc.c.i
.PHONY : src/malloc.i

# target to preprocess a source file
src/malloc.c.i:
	$(MAKE) -f CMakeFiles/liteco.dir/build.make CMakeFiles/liteco.dir/src/malloc.c.i
.PHONY : src/malloc.c.i

src/malloc.s: src/malloc.c.s
.PHONY : src/malloc.s

# target to generate assembly for a file
src/malloc.c.s:
	$(MAKE) -f CMakeFiles/liteco.dir/build.make CMakeFiles/liteco.dir/src/malloc.c.s
.PHONY : src/malloc.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... liteco"
	@echo "... rebuild_cache"
	@echo "... src/channel.o"
	@echo "... src/channel.i"
	@echo "... src/channel.s"
	@echo "... src/coroutine.o"
	@echo "... src/coroutine.i"
	@echo "... src/coroutine.s"
	@echo "... src/link.o"
	@echo "... src/link.i"
	@echo "... src/link.s"
	@echo "... src/machine.o"
	@echo "... src/machine.i"
	@echo "... src/machine.s"
	@echo "... src/malloc.o"
	@echo "... src/malloc.i"
	@echo "... src/malloc.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

